from loopy.constants.Parsing import TARGET_LAYOUT_ID_HOST, TARGET_LAYOUT_ID_PORT, TARGET_LAYOUT_ID_SERVICE

ARGUMENT_ID_HOST = '<{}>'.format(TARGET_LAYOUT_ID_HOST)
ARGUMENT_ID_PORT = '<{}>'.format(TARGET_LAYOUT_ID_PORT)
ARGUMENT_ID_SERVICE = '<{}>'.format(TARGET_LAYOUT_ID_SERVICE)