TARGET_LAYOUT_ID_HOST = 'host'
TARGET_LAYOUT_ID_PORT = 'port'
TARGET_LAYOUT_ID_SERVICE = 'service'

# This should probably go somewhere else
TARGET_LAYOUT_ID_UNKNOWN_SERVICE = 'unknown_service'

KNOWN_TARGET_LAYOUT_IDS = [
    TARGET_LAYOUT_ID_HOST, 
    TARGET_LAYOUT_ID_PORT, 
    TARGET_LAYOUT_ID_SERVICE
]

DEFAULT_TARGET_LAYOUT = KNOWN_TARGET_LAYOUT_IDS