from loopy.constants.Parsing import TARGET_LAYOUT_ID_HOST, TARGET_LAYOUT_ID_PORT, TARGET_LAYOUT_ID_SERVICE

REPORT_ID_HOST = '<{}>'.format(TARGET_LAYOUT_ID_HOST)
REPORT_ID_PORT = '<{}>'.format(TARGET_LAYOUT_ID_PORT)
REPORT_ID_SERVICE = '<{}>'.format(TARGET_LAYOUT_ID_SERVICE)